# Generated by Django 3.2.7 on 2021-10-06 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_laboratory'),
    ]

    operations = [
        migrations.AddField(
            model_name='medic',
            name='foto',
            field=models.ImageField(null=True, upload_to='', verbose_name='Agregar Foto'),
        ),
    ]
