# Generated by Django 3.2.7 on 2021-10-06 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_medic_foto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medic',
            name='foto',
            field=models.ImageField(null=True, upload_to='imgMedicos', verbose_name='Agregar Foto'),
        ),
    ]
